# Generated by Django 4.2.3 on 2023-08-31 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=11)),
                ('web', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('software', 'software'), ('hardware', 'Hardware')], max_length=8)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.distribuidor')),
            ],
        ),
    ]
