# Generated by Django 4.2.3 on 2023-08-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
